/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2GZMz74Hpzt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Gabarito } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import Link from "next/link"
import { Switch } from "@/components/ui/switch"
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"

export function Component() {
  const [isAnnual, setIsAnnual] = useState(false)
  const handlePlanToggle = (checked) => {
    setIsAnnual(checked)
  }
  const basicPrice = isAnnual ? 99 : 9
  const proPrice = isAnnual ? 199 : 19
  return (
    (<div className="flex flex-col min-h-dvh">
      <header
        className="px-4 lg:px-6 h-14 flex items-center bg-primary text-primary-foreground rounded-lg shadow-md">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <MountainIcon className="size-6 text-primary-foreground" />
          <span className="sr-only">Acme Subscription</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4 text-primary-foreground"
            prefetch={false}>
            Subscription
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4 text-primary-foreground"
            prefetch={false}>
            Details
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4 text-primary-foreground"
            prefetch={false}>
            Call to Action
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4 text-primary-foreground"
            prefetch={false}>
            Carousel
          </Link>
        </nav>
      </header>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-background">
        <div className="container px-4 md:px-6 grid grid-cols-2 gap-8">
          <div className="flex items-center justify-center">
            <div className="flex items-center justify-center">
              <MountainIcon className="size-12 text-primary" />
              <span className="sr-only">Acme Inc</span>
            </div>
          </div>
          <div className="space-y-10">
            <div
              className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Subscription Plans</h2>
                <p
                  className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Choose the plan that best fits your needs.
                </p>
              </div>
              <div className="flex items-center gap-4">
                <span className="text-sm font-medium">Monthly</span>
                <Switch id="plan-toggle" checked={isAnnual} onCheckedChange={handlePlanToggle} />
                <span className="text-sm font-medium">Annual</span>
              </div>
            </div>
            <div
              className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-2">
              <Card className="rounded-lg shadow-md">
                <CardHeader>
                  <CardTitle>Basic</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="flex items-baseline justify-center gap-2">
                    <span className="text-4xl font-bold">${basicPrice}</span>
                    <span className="text-sm text-muted-foreground">/mo</span>
                  </div>
                  <ul className="space-y-2 text-muted-foreground">
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      1 user
                    </li>
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      5 GB storage
                    </li>
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Basic support
                    </li>
                  </ul>
                </CardContent>
                <CardFooter>
                  <Button className="w-full">Subscribe</Button>
                </CardFooter>
              </Card>
              <Card className="rounded-lg shadow-md">
                <CardHeader>
                  <CardTitle>Pro</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="flex items-baseline justify-center gap-2">
                    <span className="text-4xl font-bold">${proPrice}</span>
                    <span className="text-sm text-muted-foreground">/mo</span>
                  </div>
                  <ul className="space-y-2 text-muted-foreground">
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      5 users
                    </li>
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      20 GB storage
                    </li>
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Priority support
                    </li>
                  </ul>
                </CardContent>
                <CardFooter>
                  <Button className="w-full">Subscribe</Button>
                </CardFooter>
              </Card>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
        <div className="container mx-auto px-4 md:px-6 space-y-10">
          <div className="flex flex-col items-center justify-center space-y-4 text-center w-full">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Subscription Details</h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Learn more about our subscription plans and features.
              </p>
            </div>
          </div>
          <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
            <div className="grid gap-1">
              <h3 className="text-lg font-bold">Unlimited Users</h3>
              <p className="text-muted-foreground">Our Enterprise plan allows you to add as many users as you need.</p>
            </div>
            <div className="grid gap-1">
              <h3 className="text-lg font-bold">Secure Storage</h3>
              <p className="text-muted-foreground">All your data is stored securely in our cloud infrastructure.</p>
            </div>
            <div className="grid gap-1">
              <h3 className="text-lg font-bold">Dedicated Support</h3>
              <p className="text-muted-foreground">Our Enterprise customers receive priority support from our team.</p>
            </div>
            <div className="grid gap-1">
              <h3 className="text-lg font-bold">Customization</h3>
              <p className="text-muted-foreground">
                Tailor our platform to your specific needs with our flexible features.
              </p>
            </div>
            <div className="grid gap-1">
              <h3 className="text-lg font-bold">Reporting</h3>
              <p className="text-muted-foreground">
                Get detailed insights and analytics to track your team's progress.
              </p>
            </div>
            <div className="grid gap-1">
              <h3 className="text-lg font-bold">Integrations</h3>
              <p className="text-muted-foreground">
                Seamlessly connect our platform with your existing tools and workflows.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-background">
        <div className="container mx-auto px-4 md:px-6 space-y-10">
          <div
            className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Get Started Today</h2>
              <p
                className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Fill out the form below to start your subscription.
              </p>
            </div>
          </div>
          <div className="mx-auto w-full max-w-md space-y-4">
            <Input type="text" placeholder="Name" className="w-full" />
            <Input type="email" placeholder="Email" className="w-full" />
            <Input type="tel" placeholder="Phone" className="w-full" />
            <Button className="w-full">Subscribe Now</Button>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
        <div className="container mx-auto px-4 md:px-6 space-y-10">
          <div
            className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Featured Content</h2>
              <p
                className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Check out our latest videos and blog posts.
              </p>
            </div>
          </div>
          <Carousel opts={{ align: "start", draggable: true }} className="w-full max-w-4xl transition-all duration-300 ease-in-out">
            <CarouselContent>
              <CarouselItem className="transition-transform duration-300 ease-in-out">
                <div className="p-0">
                  <Card className="border-none rounded-lg shadow-md">
                    <CardContent className="flex aspect-video items-center justify-center p-0">
                      <iframe
                        width="560"
                        height="315"
                        src="https://www.youtube.com/embed/4X1_Ku-cVK4"
                        title="YouTube video player"
                        frameBorder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                        allowFullScreen
                        className="w-full h-full"
                      ></iframe>
                    </CardContent>
                  </Card>
                </div>
              </CarouselItem>
              <CarouselItem className="transition-transform duration-300 ease-in-out">
                <div className="p-1">
                  <Card className="border-none rounded-lg shadow-md">
                    <CardContent className="flex aspect-video items-center justify-center p-6">
                      <div />
                    </CardContent>
                  </Card>
                </div>
              </CarouselItem>
            </CarouselContent>
            <CarouselPrevious />
            <CarouselNext />
          </Carousel>
        </div>
      </section>
      <footer className="bg-muted p-6 md:py-12 w-full rounded-lg shadow-md">
        <div
          className="container max-w-7xl grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-8 text-sm">
          <div className="grid gap-1">
            <h3 className="font-semibold">Company</h3>
            <Link href="#" prefetch={false}>
              About Us
            </Link>
            <Link href="#" prefetch={false}>
              Our Team
            </Link>
            <Link href="#" prefetch={false}>
              Careers
            </Link>
            <Link href="#" prefetch={false}>
              News
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Products</h3>
            <Link href="#" prefetch={false}>
              Subscription
            </Link>
            <Link href="#" prefetch={false}>
              Features
            </Link>
            <Link href="#" prefetch={false}>
              Pricing
            </Link>
            <Link href="#" prefetch={false}>
              Integrations
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Resources</h3>
            <Link href="#" prefetch={false}>
              Blog
            </Link>
            <Link href="#" prefetch={false}>
              Documentation
            </Link>
            <Link href="#" prefetch={false}>
              Support
            </Link>
            <Link href="#" prefetch={false}>
              FAQs
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Legal</h3>
            <Link href="#" prefetch={false}>
              Privacy Policy
            </Link>
            <Link href="#" prefetch={false}>
              Terms of Service
            </Link>
            <Link href="#" prefetch={false}>
              Cookie Policy
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Contact</h3>
            <Link href="#" prefetch={false}>
              Sales
            </Link>
            <Link href="#" prefetch={false}>
              Support
            </Link>
            <Link href="#" prefetch={false}>
              Partnerships
            </Link>
            <Link href="#" prefetch={false}>
              Press
            </Link>
          </div>
        </div>
      </footer>
    </div>)
  );
}

function CheckIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M20 6 9 17l-5-5" />
    </svg>)
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}
